name = "PaperMod"
license = "MIT"
licenselink = "https://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://github.com/adityatelange/hugo-PaperMod/"
min_version = "0.125.7"
