import { commentText } from "./source-comment";
import { componentName, includedComponents, type DesignSystem } from "@tesserai/core";
import { CATALOG } from "./pages/catalog";
import { printPage, type PagePrinter } from "./pages/print";
import { pagePrinting } from "./printers";
import { STORY_CONTROLLED, STORY_EXAMPLES, STORY_WIDTH, storyAxisSpec, storybookFiles, storySpec, type StorybookOptions, type StorybookResult } from "./storybook";

// The Storybook for a Vue or Svelte project: the same stories as React's (an example per
// component, every option of each axis side by side, live controls for Button, Badge and Toggle),
// with the examples printed by that framework's page printer and the stories in CSF. Svelte
// examples keep the import placeholders; the CLI resolves them as it does the components'.

const pascal = (id: string) => id.split(/[^a-zA-Z0-9]+/).filter(Boolean).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");

export function frameworkStorybookFiles(system: DesignSystem, generated: readonly { path: string; source: string }[], options: StorybookOptions & { printer: PagePrinter }): StorybookResult {
  const vue = options.framework === "vue3-vite";
  const ext = vue ? "vue" : "svelte";
  const framework = `@storybook/${options.framework}`;
  const files: { path: string; source: string }[] = [
    {
      path: ".storybook/main.ts",
      source: `// Storybook for the ${commentText(system.name)} design system, generated by tesserai. \`npx @tesserai/cli sync\` keeps it current.
import type { StorybookConfig } from "${framework}";

const config: StorybookConfig = {
  framework: "${framework}",
  stories: ["../${options.storiesDir}/**/*.stories.ts"],
  addons: ["@storybook/addon-a11y", "@storybook/addon-themes"],
};

export default config;
`,
    },
    {
      path: ".storybook/preview.ts",
      source: `import type { Preview } from "${framework}";
import { withThemeByClassName } from "@storybook/addon-themes";
// Tailwind and the system's tokens, as the app loads them.
import "${options.stylesheet}";

// The canvas is the system's page, in light and dark.
document.body.style.background = "var(--surface-page)";
document.body.style.color = "var(--color-neutral-text-strong)";

const preview: Preview = {
  globalTypes: {
    density: {
      description: "How much fits on screen",
      toolbar: {
        title: "Density",
        icon: "component",
        items: [
          { value: "compact", title: "Compact" },
          { value: "default", title: "Default" },
          { value: "comfortable", title: "Comfortable" },
        ],
        dynamicTitle: true,
      },
    },
  },
  initialGlobals: { density: "default" },
  // Dark mode is the dark class on <html>, as in the app; density its data attribute.
  decorators: [withThemeByClassName({ themes: { light: "", dark: "dark" }, defaultTheme: "light" })],
  beforeEach: ({ globals }) => {
    document.documentElement.dataset["density"] = String(globals["density"] ?? "default");
  },
  parameters: { layout: "centered", a11y: { test: "todo" } },
};

export default preview;
`,
    },
  ];
  // Svelte stories render an example at its width through one small frame.
  if (!vue) {
    files.push({
      path: `${options.storiesDir}/examples/frame.svelte`,
      source: `<script lang="ts">
  import type { Component } from "svelte";

  let { of: Of, class: className = "" }: { of: Component; class?: string } = $props();
</script>

<div class={className}><Of /></div>
`,
    });
  }

  const included = includedComponents(system);
  const covered: string[] = [];
  const uncovered: string[] = [];
  for (const [component, anatomy] of Object.entries(included)) {
    const example = STORY_EXAMPLES[component];
    if (example === undefined) {
      if (STORY_CONTROLLED[component] === undefined && component !== "direction") uncovered.push(component);
    }
    const title = componentName(component);
    const imports: string[] = [];
    const stories: string[] = [];
    const exampleFiles: { path: string; source: string }[] = [];
    const print = (spec: ReturnType<typeof storySpec>, name: string) => {
      const printed = printPage(spec, system, generated, name, { printer: options.printer });
      // A component this framework doesn't generate yet has no story.
      if (printed.problems.length > 0 || printed.source === "" || printed.missing.includes(component)) return false;
      exampleFiles.push({ path: `${options.storiesDir}/examples/${name}.${ext}`, source: printed.source });
      return true;
    };
    const width = STORY_WIDTH[component];
    // A story showing one printed example, at the component's width.
    const show = (local: string) =>
      vue
        ? `{ render: () => ({ components: { ${local} }, template: ${JSON.stringify(width === undefined ? `<${local} />` : `<div class="${width}"><${local} /></div>`)} }) }`
        : `{ render: () => ({ Component: Frame, props: { of: ${local}${width === undefined ? "" : `, class: ${JSON.stringify(width)}`} } }) }`;

    // Vue's stories share the meta's type; each Svelte story is typed by the component it renders
    // (the frame, or the playground), since Svelte's story types follow the rendered component.
    const storyType = vue ? "Story" : "StoryObj<typeof Frame>";
    if (example !== undefined && print(storySpec(example), component)) {
      imports.push(`import ${pascal(component)}Example from "./examples/${component}.${ext}";`);
      stories.push(`export const Example: ${storyType} = ${show(`${pascal(component)}Example`)};`);
      const root = storySpec(example);
      const type = root.elements[root.root]!.type;
      for (const axis of CATALOG[type]?.axes ?? []) {
        const values = anatomy.axes[axis]?.enabled ?? [];
        if (values.length < 2) continue;
        const spec = storyAxisSpec(component, type, axis, values);
        const name = `${component}-${axis}s`;
        if (spec !== null && print(spec, name)) {
          imports.push(`import ${pascal(name)} from "./examples/${name}.${ext}";`);
          stories.push(`export const ${pascal(`all-${axis}s`)}: ${storyType} = ${show(pascal(name))};`);
        }
      }
    }

    // Live controls: the component itself (Vue), or a small wrapper that takes the label (Svelte,
    // whose children are snippets a control can't give).
    const controlled = STORY_CONTROLLED[component];
    const label = component === "badge" ? "New" : component === "toggle" ? "Bold" : "Button";
    const axes = (["variant", "intent", "size"] as const).filter((axis) => (anatomy.axes[axis]?.enabled.length ?? 0) > 1);
    const args = (["variant", "intent", "size"] as const).filter((axis) => anatomy.axes[axis]?.default !== undefined).map((axis) => `${axis}: ${JSON.stringify(anatomy.axes[axis]!.default)}`);
    const argTypes = axes.map((axis) => `    ${axis}: { control: "select", options: ${JSON.stringify(anatomy.axes[axis]!.enabled)} },`);
    let meta: string;
    if (controlled !== undefined && generated.some((f) => f.path.startsWith(`components/ui/${component}/`))) {
      if (vue) {
        imports.unshift(`import { ${controlled} } from "@/components/ui/${component}";`);
        meta = `const meta = {
  title: "Components/${title}",
  component: ${controlled},
  args: { ${args.join(", ")} },
  argTypes: {
${argTypes.join("\n")}
  },
  render: (args) => ({ components: { ${controlled} }, setup: () => ({ args }), template: ${JSON.stringify(`<${controlled} v-bind="args">${label}</${controlled}>`)} }),
} satisfies Meta<typeof ${controlled}>;`;
      } else {
        exampleFiles.push({
          path: `${options.storiesDir}/examples/${component}-playground.svelte`,
          source: `<script lang="ts">
  import { ${controlled} } from "$UI$/${component}/index.js";

  let { label = ${JSON.stringify(label)}, ...rest }: { label?: string; [prop: string]: unknown } = $props();
</script>

<${controlled} {...rest}>{label}</${controlled}>
`,
        });
        imports.unshift(`import ${controlled}Playground from "./examples/${component}-playground.svelte";`);
        meta = `const meta = { title: "Components/${title}" } satisfies Meta;`;
        // The controls live on the playground story, not the examples, which have none to change.
        stories.unshift(`export const Playground: StoryObj<typeof ${controlled}Playground> = {
  args: { ${[...args, `label: ${JSON.stringify(label)}`].join(", ")} },
  argTypes: {
${argTypes.join("\n")}
  },
  render: (args) => ({ Component: ${controlled}Playground, props: args }),
};`);
      }
      if (vue) stories.unshift(`export const Playground: Story = {};`);
    } else {
      if (stories.length === 0) continue;
      meta = `const meta = { title: "Components/${title}" } satisfies Meta;`;
    }
    if (!vue && stories.some((s) => s.includes("Frame"))) imports.unshift(`import Frame from "./examples/frame.svelte";`);
    covered.push(component);
    files.push(...exampleFiles, {
      path: `${options.storiesDir}/${component}.stories.ts`,
      source: `// ${commentText(title)}, generated by tesserai from the ${commentText(system.name)} design system. \`npx @tesserai/cli sync\` keeps it current.
import type { Meta, StoryObj } from "${framework}";
${imports.join("\n")}

${meta}

export default meta;
${vue ? "type Story = StoryObj<typeof meta>;\n" : ""}
${stories.join("\n")}
`,
    });
  }
  return { files, covered, uncovered: uncovered.filter((c) => !covered.includes(c)) };
}

// The Storybook for a system in the framework its options name: React's, or Vue's or Svelte's with
// that framework's page printer.
export function storybookFilesFor(system: DesignSystem, generated: readonly { path: string; source: string }[], options: StorybookOptions): StorybookResult {
  if (options.framework === "react-vite" || options.framework === "nextjs-vite") return storybookFiles(system, generated, options);
  const printing = pagePrinting(options.framework === "vue3-vite" ? "reka-ui" : "bits-ui");
  if (printing?.printer === undefined) return { files: [], covered: [], uncovered: Object.keys(includedComponents(system)) };
  return frameworkStorybookFiles(system, generated, { ...options, printer: printing.printer });
}
