import { PRESETS } from "@tesserai/core";
import { describe, expect, it } from "vitest";
import { EXAMPLE_SPECS } from "../pages/examples";
import { printPage } from "../pages/print";
import { specBuilder } from "../pages/spec";
import { renderAll } from "../render";
import { printSveltePage } from "./page";

const system = PRESETS[0]!.build();

describe("pages printed for Svelte", () => {
  it("writes React's tree in Svelte's words: full names from the barrels, class and for, snippets for triggers, $state", async () => {
    const files = await renderAll("bits-ui", system, { format: false });
    const settings = printPage(EXAMPLE_SPECS.settings(), system, files, "settings", { printer: printSveltePage });
    expect(settings.problems).toEqual([]);
    const source = settings.source;
    expect(source.startsWith("<!-- SettingsPage: generated by tesserai")).toBe(true);
    expect(source).toContain(`import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "$UI$/alert-dialog/index.js";`);
    expect(source).toMatch(/<AlertDialogTrigger>\n\s+\{#snippet child\(\{ props \}\)\}\n\s+<Button \{\.\.\.props\} variant="outline" intent="danger">Delete<\/Button>/);
    expect(source).not.toMatch(/className=|htmlFor=|defaultValue=|defaultChecked=|asChild/);
    expect(source).toMatch(/<FieldLabel id="[a-z-]+" for="[a-z-]+">/);
    // An unbound prop is where a Svelte component starts.
    expect(source).toContain(`<Input value="Ada"`);
    expect(source).toMatch(/<Checkbox size="sm" checked \/>/);
    // Bits asks which kind of select and slider, and knows the chosen label from the root's items.
    expect(source).toMatch(/<Select value="utc" type="single" items=\{\[\{"value":"utc","label":"UTC"\}/);
    // Empty HTML elements are written open and closed (Svelte warns on <div />).
    expect(source).not.toMatch(/<(div|span|main)[^>]*\/>/);
  });

  it("keeps React state working: $state, and a setter taking a value or an update", async () => {
    const files = await renderAll("bits-ui", system, { format: false });
    const source = printPage(EXAMPLE_SPECS["data-list"](), system, files, "data-list", { printer: printSveltePage }).source;
    expect(source).toContain("let selected = $state<number[]>([1,4]);");
    expect(source).toContain("const setSelected = (next: number[] | ((current: number[]) => number[])) => (selected = typeof next === \"function\" ? next(selected) : next);");
    // Radix's three-state checkbox is Bits' checked and indeterminate.
    expect(source).toContain("checked={selected.length === 12} indeterminate={selected.length > 0 && selected.length < 12}");
  });

  it("escapes text and attributes Svelte would read as code, and says what it can't print", async () => {
    const files = await renderAll("bits-ui", system, { format: false });
    const { add, spec } = specBuilder();
    const root = add("Page", {}, [add("Text", { text: "{ braces } <b>" }), add("Button", { label: "Go" })]);
    const source = printPage(spec(root), system, files, "x", { printer: printSveltePage }).source;
    expect(source).toContain(`{"{ braces } <b>"}`);
    expect(source).not.toContain("Not printed for Svelte yet");
  });
});
