// Writes src/font-metrics-data.ts: the few numbers per font that fallback faces need (see
// src/font-metrics.ts), for the Google Fonts the builder offers and the system fonts fallbacks use.
// The numbers come from @capsizecss/metrics (MIT), which isn't a dependency: it's 28 MB unpacked
// for the ~50 KB used here. To refresh, fetch it once outside the repo and point this at it:
//
//   cd "$(mktemp -d)" && npm pack @capsizecss/metrics && tar xzf capsizecss-metrics-*.tgz
//   node <repo>/packages/core/scripts/font-metrics.mjs "$PWD/package"

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

// The local fonts a fallback face is drawn from (sans, serif, mono).
const SYSTEM = ["Arial", "Times New Roman", "Courier New"];

const pkg = process.argv[2];
if (pkg === undefined) {
  console.error("usage: node packages/core/scripts/font-metrics.mjs <path to the extracted @capsizecss/metrics package>");
  process.exit(1);
}
const { version } = JSON.parse(await readFile(join(pkg, "package.json"), "utf8"));
const { entireMetricsCollection } = await import(pathToFileURL(join(pkg, "dist/entireMetricsCollection.mjs")).href);
// Capsize keys fonts by a camelCased name ("aBeeZee" for ABeeZee); its familyName is the real
// name, which can differ from Google's list in case ("ABeeZee" vs "Abeezee"), so match without it.
const byFamily = new Map(Object.values(entireMetricsCollection).map((m) => [m.familyName.toLowerCase(), m]));
const google = JSON.parse(await readFile(new URL("../src/font-data/google-fonts.json", import.meta.url), "utf8")).map((row) => row[0]);

const rows = [];
const missing = [];
for (const family of [...google, ...SYSTEM]) {
  // The top-level numbers are the regular face's; the other weights share the vertical metrics.
  const m = byFamily.get(family.toLowerCase());
  const row = m === undefined ? undefined : [m.unitsPerEm, m.ascent, m.descent, m.lineGap, m.xWidthAvg].map((v) => Math.round(v));
  // Font units are whole numbers already; the average width is a mean, and one unit of it is well
  // under 0.1% of the em, so it's rounded too.
  if (row === undefined || !row.every(Number.isFinite) || row[0] <= 0 || row[4] <= 0) {
    missing.push(family);
    continue;
  }
  rows.push([family, ...row]);
}

const source = `// Generated by scripts/font-metrics.mjs from @capsizecss/metrics ${version}; don't edit by hand.
// Metrics from Capsize (https://github.com/seek-oss/capsize), MIT License, Copyright (c) SEEK.
// Each row: family, unitsPerEm, ascent, descent, lineGap, xWidthAvg, in font units.
export const FONT_METRICS: readonly (readonly [family: string, unitsPerEm: number, ascent: number, descent: number, lineGap: number, xWidthAvg: number])[] = [
${rows.map((r) => `  ${JSON.stringify(r).replace(/,/g, ", ")},`).join("\n")}
];
`;
await writeFile(new URL("../src/font-metrics-data.ts", import.meta.url), source);
console.log(`${rows.length} fonts written; ${missing.length} not in Capsize${missing.length === 0 ? "" : `: ${missing.join(", ")}`}`);
