import ts from "typescript";
import { describe, expect, it } from "vitest";
import { emitPlatform, platformTokens, PLATFORM_FORMATS } from "./emit-platforms";
import { PRESETS } from "./presets";

const system = PRESETS[0]!.build();

describe("platform tokens", () => {
  it("resolves colors in both schemes and sizes in px", () => {
    const t = platformTokens(system);
    expect(Object.keys(t.colors.light)).toEqual(Object.keys(t.colors.dark));
    expect(t.colors.light.primarySolid).toBeDefined();
    expect(t.colors.light.surfacePage).not.toEqual(t.colors.dark.surfacePage);
    expect(t.colors.light.brand9).toBeDefined();
    expect(t.space.s1).toBeGreaterThan(0);
    expect(t.radius.md).toBe((system.generators["radius"]!.config as { base: number }).base);
    expect(Object.keys(t.fontFamily)).toEqual(["sans", "heading", "mono"]);
  });

  it("writes every format, each in its own vocabulary", () => {
    const marker: Record<string, RegExp> = {
      scss: /\$primary-solid:/,
      ts: /primarySolid:/,
      panda: /solid: \{ value: \{ base: "#[0-9a-f]{6}", _dark: "#[0-9a-f]{6}" \} \}/,
      stylex: /primarySolid: \{ default: "#[0-9a-f]{6}", \[DARK\]: "#[0-9a-f]{6}" \}/,
      mui: /createTheme\(/,
      mantine: /primaryColor: "brand"/,
      chakra: /createSystem\(defaultConfig, config\)/,
      antd: /algorithm: theme\.darkAlgorithm/,
      swift: /static let primarySolid/,
      kotlin: /val primarySolid/,
      dart: /static const primarySolid/,
    };
    for (const format of PLATFORM_FORMATS) {
      const out = emitPlatform(system, format);
      expect(out).toContain("generated by tesserai");
      expect(out).toMatch(marker[format]!);
    }
  });

  it("writes Ant Design themes with the system's own colors, light and dark", () => {
    const out = emitPlatform(system, "antd");
    const t = platformTokens(system);
    const hexOf = (c: { r: number; g: number; b: number }) => `#${[c.r, c.g, c.b].map((v) => Math.round(v * 255).toString(16).padStart(2, "0")).join("")}`;
    const [light, dark] = out.split("export const darkTheme");
    expect(light).toContain(`colorPrimary: "${hexOf(t.colors.light.primarySolid!)}"`);
    expect(dark).toContain(`colorPrimary: "${hexOf(t.colors.dark.primarySolid!)}"`);
    expect(out).toContain(`borderRadius: ${t.radius.md}`);
    expect(out).toContain('import { theme, type ThemeConfig } from "antd";');
  });

  it("writes Panda and StyleX files that parse, nested the way each library reads them", () => {
    for (const format of ["panda", "stylex"] as const) {
      const result = ts.transpileModule(emitPlatform(system, format), { reportDiagnostics: true, compilerOptions: { strict: true, module: ts.ModuleKind.ESNext } });
      expect(result.diagnostics ?? []).toEqual([]);
    }
    // Panda's spacing keys are the utility's (p-4), not identifiers.
    expect(emitPlatform(system, "panda")).toMatch(/spacing: \{\n\s+"1": \{ value: "\d+px" \}/);
    expect(emitPlatform(system, "stylex")).toContain("stylex.createTheme(colors");
  });

  it("writes TypeScript that compiles", () => {
    const source = emitPlatform(system, "ts");
    const result = ts.transpileModule(source, { reportDiagnostics: true, compilerOptions: { strict: true, module: ts.ModuleKind.ESNext } });
    expect(result.diagnostics ?? []).toEqual([]);
    const host = ts.createCompilerHost({ strict: true, noEmit: true });
    const original = host.getSourceFile;
    host.getSourceFile = (name, lang) => (name === "theme.ts" ? ts.createSourceFile(name, source, lang) : original.call(host, name, lang));
    const program = ts.createProgram(["theme.ts"], { strict: true, noEmit: true, lib: ["lib.es2022.d.ts"], types: [] }, host);
    expect(ts.getPreEmitDiagnostics(program).map((d) => ts.flattenDiagnosticMessageText(d.messageText, "\n"))).toEqual([]);
  });
});
