import { includedComponents, type DesignSystem } from "./system";

// The @shadcn/lint version the generated config is written for; the linter is young and its API may change.
export const SHADCN_LINT_VERSION = "0.2.0";

export type LintOptions = {
  // Import prefix of the generated components, e.g. "@/components/ui".
  ui: string;
  // Glob of the generated components folder, e.g. "src/components/ui/**".
  componentsGlob: string;
  // Folders held to warnings rather than errors, and folders exempt entirely.
  legacy?: string[];
  exempt?: string[];
  // A Vue or Svelte project: its single-file components are linted too, through their parser.
  framework?: "vue" | "svelte";
};

// The parser package @shadcn/lint reads each framework's components with.
export const LINT_PARSERS = { vue: "vue-eslint-parser", svelte: "svelte-eslint-parser" } as const;

// The linter appends this to every message, so it stays one sentence; the rule messages already
// name the component's variants and sizes, and AGENTS.md carries the full list.
export function lintGuidance(system: DesignSystem): string {
  return `This project uses the "${system.name}" design system generated by tesserai (intents: ${Object.keys(system.intents).join(", ")}); use variant, intent and size props and theme utilities, never raw values. See AGENTS.md and tesserai/design-system.json.`;
}

// A fuller description for documentation: every component with its enabled axes.
export function lintComponentSummary(system: DesignSystem): string {
  return Object.values(includedComponents(system))
    .map((a) => {
      const axes = (["variant", "intent", "size"] as const)
        .flatMap((axis) => {
          const enabled = a.axes[axis]?.enabled;
          return enabled === undefined ? [] : [`${axis}: ${enabled.join("/")}`];
        })
        .join(", ");
      return axes === "" ? a.name : `${a.name} (${axes})`;
    })
    .join("; ");
}

type Severity = "error" | "warn";

function rules(severity: Severity): Record<string, unknown> {
  return {
    "shadcn/no-restyle": [severity, { allow: ["layout"], message: { spacing: "Use a {{component}} size instead: {{sizes}}." } }],
    "shadcn/no-raw-colors": severity,
    "shadcn/no-arbitrary-values": [severity, { allow: ["layout"] }],
    "shadcn/no-inline-styles": severity,
    "shadcn/no-unknown-classes": severity,
    "shadcn/require-static-classes": severity,
  };
}

// Inside the generated components restyling and arbitrary values are how the components are built,
// and so are inline styles: values computed at run time (a progress bar's position, a toggle
// group's spacing, a toaster's variables) and the styles a primitive's own markup carries (Radix's
// pointer-events and display, which the Vue and Svelte ports write out), plus hook classes a library
// reads (sonner's "toaster"): the linter would fail a fresh install on them. Raw colors stay
// forbidden there too.
const COMPONENT_RULES: Record<string, unknown> = {
  "shadcn/no-restyle": "off",
  "shadcn/no-arbitrary-values": "off",
  "shadcn/require-static-classes": "off",
  "shadcn/no-inline-styles": "off",
  "shadcn/no-unknown-classes": "off",
};

const OFF_RULES: Record<string, unknown> = Object.fromEntries(Object.keys(rules("error")).map((r) => [r, "off"]));

export function lintSettings(system: DesignSystem, options: LintOptions): Record<string, unknown> {
  return {
    shadcn: {
      ui: options.ui,
      mergeFunctions: ["cn"],
      variantFunctions: ["cva"],
      note: lintGuidance(system),
    },
  };
}

// What frameworks build into the project folder (ESLint skips only node_modules and .git): linting
// it fails on minified code and on directives for rules this config doesn't load.
export const LINT_IGNORES = ["dist/**", "build/**", ".output/**", ".nuxt/**", ".next/**", ".svelte-kit/**", ".vercel/**", ".netlify/**", "storybook-static/**", "public/build/**", "coverage/**"];

export function emitEslintConfig(system: DesignSystem, options: LintOptions): string {
  const blocks: Record<string, unknown>[] = [
    { ignores: LINT_IGNORES },
    {
      files: ["**/*.{js,jsx,ts,tsx}"],
      languageOptions: { parser: "__TS_PARSER__", parserOptions: { ecmaFeatures: { jsx: true } } },
      plugins: { shadcn: "__SHADCN__" },
      settings: lintSettings(system, options),
      rules: rules("error"),
    },
    // Vue's and Svelte's components, their templates included, through the framework's parser
    // with TypeScript inside, as @shadcn/lint documents.
    ...(options.framework === undefined
      ? []
      : [
          {
            files: [`**/*.${options.framework}`],
            languageOptions: { parser: "__FRAMEWORK_PARSER__", parserOptions: { parser: "__TS_PARSER__" } },
            plugins: { shadcn: "__SHADCN__" },
            settings: lintSettings(system, options),
            rules: rules("error"),
          },
        ]),
    { files: [options.componentsGlob], rules: COMPONENT_RULES },
    ...(options.legacy?.length ? [{ files: options.legacy, rules: rules("warn") }] : []),
    ...(options.exempt?.length ? [{ files: options.exempt, rules: OFF_RULES }] : []),
  ];
  const body = JSON.stringify(blocks, null, 2).replaceAll('"__TS_PARSER__"', "tsParser").replaceAll('"__SHADCN__"', "shadcn").replace('"__FRAMEWORK_PARSER__"', "frameworkParser");
  return `// Generated by tesserai from tesserai/design-system.json for @shadcn/lint ${SHADCN_LINT_VERSION}. Do not edit; run npx @tesserai/cli sync.
import { plugin as shadcn } from "@shadcn/lint";
import tsParser from "@typescript-eslint/parser";
import { defineConfig } from "eslint/config";${options.framework === undefined ? "" : `
import frameworkParser from "${LINT_PARSERS[options.framework]}";`}

export default defineConfig(${body});
`;
}

export function emitOxlintConfig(system: DesignSystem, options: LintOptions): string {
  const config = {
    jsPlugins: ["@shadcn/lint"],
    ignorePatterns: LINT_IGNORES,
    settings: lintSettings(system, options),
    rules: rules("error"),
    overrides: [
      { files: [options.componentsGlob], rules: COMPONENT_RULES },
      ...(options.legacy?.length ? [{ files: options.legacy, rules: rules("warn") }] : []),
      ...(options.exempt?.length ? [{ files: options.exempt, rules: OFF_RULES }] : []),
    ],
  };
  return JSON.stringify(config, null, 2) + "\n";
}
