import { z } from "zod";

// Pages saved with a system: layouts built from the system's own components (generated by the AI or,
// later, by hand), in json-render's spec format. They use the system rather than define it, so
// nothing generated from the system (tokens, CSS, components) reads them; the preview and the page
// printer do (packages/templates/src/pages). Core checks only the shape; whether each element is a
// real catalog entry with valid props is checked by the printer, which knows the catalog.

export const MAX_PAGES = 30;
// The example pages the preview always has; a saved page never takes one of their ids.
export const EXAMPLE_PAGE_IDS = ["sign-in", "settings", "dashboard", "data-list"] as const;
export const MAX_PAGE_ELEMENTS = 300;

export const SavedPageElement = z
  .object({
    type: z.string().min(1).max(64),
    props: z.record(z.string(), z.unknown()).default({}),
    children: z.array(z.string()).optional(),
    slots: z.record(z.string(), z.array(z.string())).optional(),
  })
  .strict();

export const SavedPageSpec = z
  .object({ root: z.string().min(1), elements: z.record(z.string(), SavedPageElement) })
  .strict()
  .refine((s) => Object.keys(s.elements).length <= MAX_PAGE_ELEMENTS, `a page has at most ${MAX_PAGE_ELEMENTS} elements`);

export const SavedPage = z
  .object({
    name: z.string().min(1).max(60),
    // What was asked for, when the AI made it.
    prompt: z.string().max(4000).optional(),
    spec: SavedPageSpec,
  })
  .strict();
export type SavedPage = z.infer<typeof SavedPage>;

export const PageId = z.string().regex(/^[a-z][a-z0-9-]{0,39}$/, "lowercase letters, digits and dashes, starting with a letter");

// An id for a new page from its name, not already taken.
export function pageIdFor(name: string, taken: Iterable<string>): string {
  const used = new Set(taken);
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").replace(/^[^a-z]+/, "").slice(0, 32) || "page";
  let id = slug;
  for (let n = 2; used.has(id); n++) id = `${slug}-${n}`;
  return id;
}
