// Writes src/tailwind-colors.ts from the installed Tailwind v4's own theme.css, so `import` knows
// what bg-red-600 is in a project that uses Tailwind's built-in colors.
// node packages/cli/scripts/tailwind-colors.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const pkg = require.resolve("tailwindcss/package.json");
const { version } = JSON.parse(readFileSync(pkg, "utf8"));
const css = readFileSync(join(dirname(pkg), "theme.css"), "utf8");
const colors = {};
for (const m of css.matchAll(/--color-([a-z]+(?:-\d+)?):\s*([^;]+);/g)) colors[m[1]] = m[2].trim();
const body = Object.entries(colors).map(([k, v]) => `  "${k}": "${v}",`).join("\n");
writeFileSync(
  new URL("../src/tailwind-colors.ts", import.meta.url),
  `// Generated by scripts/tailwind-colors.mjs from tailwindcss ${version} theme.css. Don't edit.\nexport const TAILWIND_COLORS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`${Object.keys(colors).length} colors from tailwindcss ${version}`);
